// ============================================================
// 감사 대상 소스 스냅샷 — Phase1 펌웨어/소스를 TS 문자열 모듈로 굳혀
// 브라우저 정적분석기가 실 내용을 읽게 한다. 소스 변경 시 재실행:
//   pnpm --filter @station/audit-kit snapshot
// ============================================================
import { readFileSync, readdirSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const here = fileURLToPath(new URL(".", import.meta.url));
const ROOT = join(here, "..", "..", ".."); // repo root

// 감사 대상 디렉터리(확장자 화이트리스트).
const ROOTS = ["firmware", "ros2", "vision", "telemetry"];
const EXT = new Set([".c", ".h", ".cpp", ".hpp", ".py"]);

function walk(dir, acc) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) {
      if (name === "node_modules" || name === "__pycache__") continue;
      walk(p, acc);
    } else {
      const dot = name.lastIndexOf(".");
      if (dot >= 0 && EXT.has(name.slice(dot))) acc.push(p);
    }
  }
}

const files = [];
for (const r of ROOTS) {
  const abs = join(ROOT, r);
  try {
    statSync(abs);
    walk(abs, files);
  } catch {
    /* dir 없음 — skip */
  }
}
files.sort();

const entries = files
  .map((abs) => {
    const key = relative(ROOT, abs).split("\\").join("/");
    const src = readFileSync(abs, "utf8");
    return `  ${JSON.stringify(key)}: ${JSON.stringify(src)},`;
  })
  .join("\n");

const out = `/* AUTO-GENERATED by scripts/snapshot-sources.mjs — DO NOT EDIT.
   감사 대상 소스 스냅샷(브라우저 정적분석 입력). 재생성: pnpm --filter @station/audit-kit snapshot */
export const SAMPLES: Record<string, string> = {
${entries}
};
`;

const dest = join(here, "..", "src", "samples.generated.ts");
writeFileSync(dest, out);
console.log(`snapshot: ${files.length} files → src/samples.generated.ts`);
